#! /bin/sh

# Xboxdrv daemon suspend/resume

case $1 in
     suspend|suspend_hybrid|hibernate)
        if ps aux | grep "xboxdrv" > /dev/null
        then
            service xboxdrv stop
        fi
        ;;
     resume|thaw)
	service xboxdrv restart
        ;;
esac
